name: 'Agent Metadata Action'
description: 'Fetches agent configuration metadata from a checked-out repository'
inputs:
  cache:
    description: 'Enable Go build cache'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.action_path }}/go.mod'
        cache: ${{ inputs.cache }}
    
    - name: Build and Run
      id: run-action
      shell: bash
      run: |
        set -e
        cd ${{ github.action_path }}
        # todo - look at using a built image instead
        go build -o agent-metadata-action ./cmd/agent-metadata-action
        ./agent-metadata-action
