name: 'Agent Metadata Action'
description: 'Fetches agent configuration metadata to create/update NEGP entities in NR'
inputs:
  agent-type:
    description: 'The type of agent in all lowercase eg. dotnet'
    required: false
    default: ''
  version:
    description: 'Agent version in semver format (ex. 1.2.3 or v1.2.3). The action will prepend "v" if not present for tag checkout.'
    required: false
    default: ''
  cache:
    description: 'Enable Go build cache'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Normalize version tag for checkout
      id: version
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [[ -n "$VERSION" && ! "$VERSION" =~ ^v ]]; then
          echo "ref=v${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "ref=${VERSION}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.version.outputs.ref }} # When ref is empty (as in docs scenario), this will default to checking out the commit that triggered the action

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.action_path }}/go.mod'
        cache: ${{ inputs.cache }}
    
    - name: Build and Run
      id: run-action
      shell: bash
      env:
        INPUT_AGENT_TYPE: ${{ inputs.agent-type }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        set -e
        cd ${{ github.action_path }}
        # todo - look at using a built image instead
        go build -o agent-metadata-action ./cmd/agent-metadata-action
        ./agent-metadata-action
