name: 'Agent Metadata Action'
description: 'Fetches agent configuration metadata to create/update NEGP entities in NR'
inputs:
  agent-type:
    description: 'The type of agent in all lowercase eg. dotnet'
    required: true
    default: ''
  version:
    description: 'Agent version in strict semver format MAJOR.MINOR.PATCH (ex. 1.2.3)'
    required: true
    default: ''
  features:
    description: 'Comma-separated list of features to include in the agent (ex. feature1,feature2)'
    required: false
    default: ''
  bugs:
    description: 'Comma-separated list of bugs to exclude from the agent (ex. bug1,bug2)'
    required: false
    default: ''
  security:
    description: 'Comma-separated list of security fixes (ex. fix1,fix2)'
    required: false
    default: ''
  cache:
    description: 'Enable Go build cache'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.action_path }}/go.mod'
        cache: ${{ inputs.cache }}
    
    - name: Build and Run
      id: run-action
      shell: bash
      run: |
        set -e
        cd ${{ github.action_path }}
        # todo - look at using a built image instead
        go build -o agent-metadata-action ./cmd/agent-metadata-action
        ./agent-metadata-action
